language: c

sudo: required

dist: trusty

before_install:
  - curl -OL http://raw.github.com/craigcitro/r-travis/master/scripts/travis-tool.sh
  - chmod 755 ./travis-tool.sh
  - ./travis-tool.sh bootstrap

install:
  - ./travis-tool.sh install_r testthat
  - ./travis-tool.sh install_r devtools
  - pip install dropbox

script: 
  #- Rscript -e "library(testthat);test_dir('.')"
  - Rscript -e "source('download.r')"
  - python upload.py

notifications:
  email: false
