language: c

sudo: required
before_install:
  - curl -OL http://raw.github.com/craigcitro/r-travis/master/scripts/travis-tool.sh
  - chmod 755 ./travis-tool.sh
  - ./travis-tool.sh bootstrap

install:
  - ./travis-tool.sh install_r testthat

script: 
  - Rscript -e "library(testthat);test_dir('.')"
  - Rscript -e "install.packages("devtools", dependencies = TRUE)"
  - Rscript -e "require(devtools)"
  - Rscript -e "install_github("rfigshare","ropensci")"
  - Rscript -e "require(rfigshare)"

notifications:
  email: false
